return module.exports=[{code: 'AF', name: 'Afganistán'},
{code: 'AL', name: 'Albania'},
{code: 'DE', name: 'Alemania'},
{code: 'AD', name: 'Andorra'},
{code: 'AO', name: 'Angola'},
{code: 'AI', name: 'Anguilla'},
{code: 'AQ', name: 'Antártida'},
{code: 'AG', name: 'Antigua y Barbuda'},
{code: 'AN', name: 'Antillas Holandesas'},
{code: 'SA', name: 'Arabia Saudí'},
{code: 'DZ', name: 'Argelia'},
{code: 'AR', name: 'Argentina'},
{code: 'AM', name: 'Armenia'},
{code: 'AW', name: 'Aruba'},
{code: 'AU', name: 'Australia'},
{code: 'AT', name: 'Austria'},
{code: 'AZ', name: 'Azerbaiyán'},
{code: 'BS', name: 'Bahamas'},
{code: 'BH', name: 'Bahrein'},
{code: 'BD', name: 'Bangladesh'},
{code: 'BB', name: 'Barbados'},
{code: 'BE', name: 'Bélgica'},
{code: 'BZ', name: 'Belice'},
{code: 'BJ', name: 'Benin'},
{code: 'BM', name: 'Bermudas'},
{code: 'BY', name: 'Bielorrusia'},
{code: 'MM', name: 'Birmania'},
{code: 'BO', name: 'Bolivia'},
{code: 'BA', name: 'Bosnia y Herzegovina'},
{code: 'BW', name: 'Botswana'},
{code: 'BR', name: 'Brasil'},
{code: 'BN', name: 'Brunei'},
{code: 'BG', name: 'Bulgaria'},
{code: 'BF', name: 'Burkina Faso'},
{code: 'BI', name: 'Burundi'},
{code: 'BT', name: 'Bután'},
{code: 'CV', name: 'Cabo Verde'},
{code: 'KH', name: 'Camboya'},
{code: 'CM', name: 'Camerún'},
{code: 'CA', name: 'Canadá'},
{code: 'TD', name: 'Chad'},
{code: 'CL', name: 'Chile'},
{code: 'CN', name: 'China'},
{code: 'CY', name: 'Chipre'},
{code: 'VA', name: 'Ciudad del Vaticano (Santa Sede)'},
{code: 'CO', name: 'Colombia'},
{code: 'KM', name: 'Comores'},
{code: 'CG', name: 'Congo'},
{code: 'CD', name: 'Congo, República Democrática del'},
{code: 'KR', name: 'Corea'},
{code: 'KP', name: 'Corea del Norte'},
{code: 'CI', name: 'Costa de Marfíl'},
{code: 'CR', name: 'Costa Rica'},
{code: 'HR', name: 'Croacia (Hrvatska)'},
{code: 'CU', name: 'Cuba'},
{code: 'CW', name: 'Curaçao'},
{code: 'DK', name: 'Dinamarca'},
{code: 'DJ', name: 'Djibouti'},
{code: 'DM', name: 'Dominica'},
{code: 'EC', name: 'Ecuador'},
{code: 'EG', name: 'Egipto'},
{code: 'SV', name: 'El Salvador'},
{code: 'AE', name: 'Emiratos Árabes Unidos'},
{code: 'ER', name: 'Eritrea'},
{code: 'SI', name: 'Eslovenia'},
{code: 'ES', name: 'España - Península y Baleares'},
{code: 'ES_CANARY', name: 'España - Islas Canarias'},
{code: 'US', name: 'Estados Unidos'},
{code: 'EE', name: 'Estonia'},
{code: 'ET', name: 'Etiopía'},
{code: 'FJ', name: 'Fiji'},
{code: 'PH', name: 'Filipinas'},
{code: 'FI', name: 'Finlandia'},
{code: 'FR', name: 'Francia'},
{code: 'GA', name: 'Gabón'},
{code: 'GM', name: 'Gambia'},
{code: 'GE', name: 'Georgia'},
{code: 'GH', name: 'Ghana'},
{code: 'GI', name: 'Gibraltar'},
{code: 'GD', name: 'Granada'},
{code: 'GR', name: 'Grecia'},
{code: 'GL', name: 'Groenlandia'},
{code: 'GP', name: 'Guadalupe'},
{code: 'GU', name: 'Guam'},
{code: 'GT', name: 'Guatemala'},
{code: 'GY', name: 'Guyana'},
{code: 'GF', name: 'Guayana Francesa'},
{code: 'GN', name: 'Guinea'},
{code: 'GQ', name: 'Guinea Ecuatorial'},
{code: 'GW', name: 'Guinea-Bissau'},
{code: 'HT', name: 'Haití'},
{code: 'HN', name: 'Honduras'},
{code: 'HK', name: 'Hong Kong'},
{code: 'HU', name: 'Hungría'},
{code: 'IN', name: 'India'},
{code: 'ID', name: 'Indonesia'},
{code: 'IQ', name: 'Irak'},
{code: 'IR', name: 'Irán'},
{code: 'IE', name: 'Irlanda'},
{code: 'BV', name: 'Isla Bouvet'},
{code: 'CX', name: 'Isla de Christmas'},
{code: 'IS', name: 'Islandia'},
{code: 'KY', name: 'Islas Caimán'},
{code: 'CK', name: 'Islas Cook'},
{code: 'CC', name: 'Islas de Cocos o Keeling'},
{code: 'FO', name: 'Islas Faroe'},
{code: 'HM', name: 'Islas Heard y McDonald'},
{code: 'FK', name: 'Islas Malvinas'},
{code: 'MP', name: 'Islas Marianas del Norte'},
{code: 'MH', name: 'Islas Marshall'},
{code: 'UM', name: 'Islas menores de Estados Unidos'},
{code: 'PW', name: 'Islas Palau'},
{code: 'SB', name: 'Islas Salomón'},
{code: 'SJ', name: 'Islas Svalbard y Jan Mayen'},
{code: 'TK', name: 'Islas Tokelau'},
{code: 'TC', name: 'Islas Turks y Caicos'},
{code: 'VI', name: 'Islas Vírgenes (EE.UU.)'},
{code: 'VG', name: 'Islas Vírgenes (Reino Unido)'},
{code: 'WF', name: 'Islas Wallis y Futuna'},
{code: 'IL', name: 'Israel'},
{code: 'IT', name: 'Italia'},
{code: 'JM', name: 'Jamaica'},
{code: 'JP', name: 'Japón'},
{code: 'JO', name: 'Jordania'},
{code: 'KZ', name: 'Kazajistán'},
{code: 'KE', name: 'Kenia'},
{code: 'KG', name: 'Kirguizistán'},
{code: 'KI', name: 'Kiribati'},
{code: 'KW', name: 'Kuwait'},
{code: 'LA', name: 'Laos'},
{code: 'LS', name: 'Lesotho'},
{code: 'LV', name: 'Letonia'},
{code: 'LB', name: 'Líbano'},
{code: 'LR', name: 'Liberia'},
{code: 'LY', name: 'Libia'},
{code: 'LI', name: 'Liechtenstein'},
{code: 'LT', name: 'Lituania'},
{code: 'LU', name: 'Luxemburgo'},
{code: 'MK', name: 'Macedonia, Ex-República Yugoslava de'},
{code: 'MG', name: 'Madagascar'},
{code: 'MY', name: 'Malasia'},
{code: 'MW', name: 'Malawi'},
{code: 'MV', name: 'Maldivas'},
{code: 'ML', name: 'Malí'},
{code: 'MT', name: 'Malta'},
{code: 'MA', name: 'Marruecos'},
{code: 'MQ', name: 'Martinica'},
{code: 'MU', name: 'Mauricio'},
{code: 'MR', name: 'Mauritania'},
{code: 'YT', name: 'Mayotte'},
{code: 'MX', name: 'México'},
{code: 'FM', name: 'Micronesia'},
{code: 'MD', name: 'Moldavia'},
{code: 'MC', name: 'Mónaco'},
{code: 'MN', name: 'Mongolia'},
{code: 'ME', name: 'Montenegro'},
{code: 'MS', name: 'Montserrat'},
{code: 'MZ', name: 'Mozambique'},
{code: 'NA', name: 'Namibia'},
{code: 'NR', name: 'Nauru'},
{code: 'NP', name: 'Nepal'},
{code: 'NI', name: 'Nicaragua'},
{code: 'NE', name: 'Níger'},
{code: 'NG', name: 'Nigeria'},
{code: 'NU', name: 'Niue'},
{code: 'NF', name: 'Norfolk'},
{code: 'NO', name: 'Noruega'},
{code: 'NC', name: 'Nueva Caledonia'},
{code: 'NZ', name: 'Nueva Zelanda'},
{code: 'OM', name: 'Omán'},
{code: 'NL', name: 'Holanda'},
{code: 'PA', name: 'Panamá'},
{code: 'PG', name: 'Papúa Nueva Guinea'},
{code: 'PK', name: 'Paquistán'},
{code: 'PY', name: 'Paraguay'},
{code: 'PE', name: 'Perú'},
{code: 'PN', name: 'Pitcairn'},
{code: 'PF', name: 'Polinesia Francesa'},
{code: 'PL', name: 'Polonia'},
{code: 'PT', name: 'Portugal'},
{code: 'PR', name: 'Puerto Rico'},
{code: 'QA', name: 'Qatar'},
{code: 'GB', name: 'Reino Unido'},
{code: 'CF', name: 'República Centroafricana'},
{code: 'CZ', name: 'República Checa'},
{code: 'ZA', name: 'República de Sudáfrica'},
{code: 'DO', name: 'República Dominicana'},
{code: 'SK', name: 'República Eslovaca'},
{code: 'RE', name: 'Reunión'},
{code: 'RW', name: 'Ruanda'},
{code: 'RO', name: 'Rumania'},
{code: 'RU', name: 'Rusia'},
{code: 'EH', name: 'Sahara Occidental'},
{code: 'KN', name: 'Saint Kitts y Nevis'},
{code: 'WS', name: 'Samoa'},
{code: 'AS', name: 'Samoa Americana'},
{code: 'SM', name: 'San Marino'},
{code: 'VC', name: 'San Vicente y Granadinas'},
{code: 'SH', name: 'Santa Helena'},
{code: 'LC', name: 'Santa Lucía'},
{code: 'ST', name: 'Santo Tomé y Príncipe'},
{code: 'SN', name: 'Senegal'},
{code: 'RS', name: 'Serbia'},
{code: 'SC', name: 'Seychelles'},
{code: 'SL', name: 'Sierra Leona'},
{code: 'SG', name: 'Singapur'},
{code: 'SY', name: 'Siria'},
{code: 'SO', name: 'Somalia'},
{code: 'LK', name: 'Sri Lanka'},
{code: 'PM', name: 'St. Pierre y Miquelon'},
{code: 'SZ', name: 'Suazilandia'},
{code: 'SD', name: 'Sudán'},
{code: 'SE', name: 'Suecia'},
{code: 'CH', name: 'Suiza'},
{code: 'SR', name: 'Surinam'},
{code: 'TH', name: 'Tailandia'},
{code: 'TW', name: 'Taiwán'},
{code: 'TZ', name: 'Tanzania'},
{code: 'TJ', name: 'Tayikistán'},
{code: 'TF', name: 'Territorios franceses del Sur'},
{code: 'TP', name: 'Timor Oriental'},
{code: 'TG', name: 'Togo'},
{code: 'TO', name: 'Tonga'},
{code: 'TT', name: 'Trinidad y Tobago'},
{code: 'TN', name: 'Túnez'},
{code: 'TM', name: 'Turkmenistán'},
{code: 'TR', name: 'Turquía'},
{code: 'TV', name: 'Tuvalu'},
{code: 'UA', name: 'Ucrania'},
{code: 'UG', name: 'Uganda'},
{code: 'UY', name: 'Uruguay'},
{code: 'UZ', name: 'Uzbekistán'},
{code: 'VU', name: 'Vanuatu'},
{code: 'VE', name: 'Venezuela'},
{code: 'VN', name: 'Vietnam'},
{code: 'YE', name: 'Yemen'},
{code: 'YU', name: 'Yugoslavia'},
{code: 'ZM', name: 'Zambia'},
{code: 'ZW', name: 'Zimbabue'}]